import {
  agentProtocolInventoryResponseSchema,
  connectorReadinessResponseSchema,
  createManagementConnectorRequestSchema,
  createWebhookEndpointRequestSchema,
  idParam,
  jsonBody,
  listConnectorTemplatesResponseSchema,
  listManagementConnectorsResponseSchema,
  listWebhookEndpointsQuerySchema,
  listWebhookEndpointsResponseSchema,
  listWebhookRequestsQuerySchema,
  listWebhookRequestsResponseSchema,
  type ManagementRouteConfig,
  managementAccountCenterSettingsResponseSchema,
  managementBrandingSettingsResponseSchema,
  managementConnectorResponseSchema,
  managementReadinessResponseSchema,
  managementSignInSettingsResponseSchema,
  multipartBody,
  paginationQuerySchema,
  updateManagementAccountCenterSettingsRequestSchema,
  updateManagementBrandingSettingsRequestSchema,
  updateManagementConnectorRequestSchema,
  updateManagementSignInSettingsRequestSchema,
  updateWebhookEndpointRequestSchema,
  uploadedAssetResponseSchema,
  webhookEndpointSchema,
  webhookEndpointSecretResponseSchema,
  webhookRequestSchema,
} from './helpers'

export const platformWebhookRoutes: ManagementRouteConfig[] = [
  {
    method: 'get',
    path: '/connectors',
    operationId: 'listConnectors',
    summary: 'List connectors',
    request: { query: paginationQuerySchema },
    response: listManagementConnectorsResponseSchema,
  },
  {
    method: 'post',
    path: '/connectors',
    operationId: 'createConnector',
    summary: 'Create connector',
    request: { body: jsonBody(createManagementConnectorRequestSchema) },
    response: managementConnectorResponseSchema,
    status: 201,
  },
  {
    method: 'get',
    path: '/connectors/{id}',
    operationId: 'getConnector',
    summary: 'Get connector',
    request: { params: idParam },
    response: managementConnectorResponseSchema,
  },
  {
    method: 'patch',
    path: '/connectors/{id}',
    operationId: 'updateConnector',
    summary: 'Update connector',
    request: { params: idParam, body: jsonBody(updateManagementConnectorRequestSchema) },
    response: managementConnectorResponseSchema,
  },
  {
    method: 'delete',
    path: '/connectors/{id}',
    operationId: 'deleteConnector',
    summary: 'Delete connector',
    request: { params: idParam },
    noBody: true,
  },
  {
    method: 'get',
    path: '/connectors/{id}/readiness',
    operationId: 'listConnectorReadiness',
    summary: 'Get connector readiness',
    request: { params: idParam },
    response: connectorReadinessResponseSchema,
  },
  {
    method: 'get',
    path: '/connectors/templates',
    operationId: 'listConnectorTemplates',
    summary: 'List connector templates',
    response: listConnectorTemplatesResponseSchema,
  },

  {
    method: 'get',
    path: '/sign-in-settings',
    operationId: 'getSignInSettings',
    summary: 'Get sign-in settings',
    response: managementSignInSettingsResponseSchema,
  },
  {
    method: 'patch',
    path: '/sign-in-settings',
    operationId: 'updateSignInSettings',
    summary: 'Update sign-in settings',
    request: { body: jsonBody(updateManagementSignInSettingsRequestSchema) },
    response: managementSignInSettingsResponseSchema,
  },
  {
    method: 'get',
    path: '/branding-settings',
    operationId: 'getBrandingSettings',
    summary: 'Get branding settings',
    response: managementBrandingSettingsResponseSchema,
  },
  {
    method: 'patch',
    path: '/branding-settings',
    operationId: 'updateBrandingSettings',
    summary: 'Update branding settings',
    request: { body: jsonBody(updateManagementBrandingSettingsRequestSchema) },
    response: managementBrandingSettingsResponseSchema,
  },
  {
    method: 'get',
    path: '/account-center-settings',
    operationId: 'getAccountCenterSettings',
    summary: 'Get account center settings',
    response: managementAccountCenterSettingsResponseSchema,
  },
  {
    method: 'patch',
    path: '/account-center-settings',
    operationId: 'updateAccountCenterSettings',
    summary: 'Update account center settings',
    request: { body: jsonBody(updateManagementAccountCenterSettingsRequestSchema) },
    response: managementAccountCenterSettingsResponseSchema,
  },
  {
    method: 'post',
    path: '/branding/logo',
    operationId: 'uploadBrandingLogo',
    summary: 'Upload branding logo',
    request: { body: multipartBody() },
    response: uploadedAssetResponseSchema,
    status: 201,
  },
  {
    method: 'post',
    path: '/branding/favicon',
    operationId: 'uploadBrandingFavicon',
    summary: 'Upload branding favicon',
    request: { body: multipartBody() },
    response: uploadedAssetResponseSchema,
    status: 201,
  },
  {
    method: 'get',
    path: '/readiness',
    operationId: 'getReadiness',
    summary: 'Get deployment readiness',
    response: managementReadinessResponseSchema,
  },
  {
    method: 'get',
    path: '/agents/protocol-inventory',
    operationId: 'getAgentProtocolInventory',
    summary: 'List delegated agent protocol inventory',
    request: { query: paginationQuerySchema },
    response: agentProtocolInventoryResponseSchema,
  },
  {
    method: 'delete',
    path: '/agents/{id}',
    operationId: 'revokeAgent',
    summary: 'Revoke delegated agent access',
    request: { params: idParam },
    noBody: true,
  },
  {
    method: 'delete',
    path: '/agent-hosts/{id}',
    operationId: 'revokeAgentHost',
    summary: 'Revoke delegated agent host access',
    request: { params: idParam },
    noBody: true,
  },
  {
    method: 'delete',
    path: '/agent-capability-grants/{id}',
    operationId: 'revokeAgentCapabilityGrant',
    summary: 'Revoke delegated agent capability grant',
    request: { params: idParam },
    noBody: true,
  },

  {
    method: 'get',
    path: '/webhooks/endpoints',
    operationId: 'listWebhookEndpoints',
    summary: 'List webhook endpoints',
    request: { query: listWebhookEndpointsQuerySchema },
    response: listWebhookEndpointsResponseSchema,
  },
  {
    method: 'post',
    path: '/webhooks/endpoints',
    operationId: 'createWebhookEndpoint',
    summary: 'Create webhook endpoint',
    request: { body: jsonBody(createWebhookEndpointRequestSchema) },
    response: webhookEndpointSecretResponseSchema,
    status: 201,
  },
  {
    method: 'get',
    path: '/webhooks/endpoints/{id}',
    operationId: 'getWebhookEndpoint',
    summary: 'Get webhook endpoint',
    request: { params: idParam },
    response: webhookEndpointSchema,
  },
  {
    method: 'patch',
    path: '/webhooks/endpoints/{id}',
    operationId: 'updateWebhookEndpoint',
    summary: 'Update webhook endpoint',
    request: { params: idParam, body: jsonBody(updateWebhookEndpointRequestSchema) },
    response: webhookEndpointSchema,
  },
  {
    method: 'delete',
    path: '/webhooks/endpoints/{id}',
    operationId: 'deleteWebhookEndpoint',
    summary: 'Delete webhook endpoint',
    request: { params: idParam },
    noBody: true,
  },
  {
    method: 'post',
    path: '/webhooks/endpoints/{id}/secrets',
    operationId: 'rotateWebhookEndpointSecret',
    summary: 'Rotate webhook endpoint secret',
    request: { params: idParam },
    response: webhookEndpointSecretResponseSchema,
    status: 201,
  },
  {
    method: 'get',
    path: '/webhooks/requests',
    operationId: 'listWebhookRequests',
    summary: 'List webhook requests',
    request: { query: listWebhookRequestsQuerySchema },
    response: listWebhookRequestsResponseSchema,
  },
  {
    method: 'get',
    path: '/webhooks/requests/{id}',
    operationId: 'getWebhookRequest',
    summary: 'Get webhook request',
    request: { params: idParam },
    response: webhookRequestSchema,
  },
  {
    method: 'post',
    path: '/webhooks/requests/{id}/retries',
    operationId: 'retryWebhookRequest',
    summary: 'Retry webhook request',
    request: { params: idParam },
    response: webhookRequestSchema,
    status: 202,
  },
]
