name = "flareauth"
main = "./server/worker.ts"
compatibility_date = "2026-04-12"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
preview_urls = true

[vars]
EMAIL_FROM = "noreply@fa.tftt.cc"
EMAIL_FROM_NAME = "FlareAuth"

[assets]
binding = "ASSETS"
directory = "./dist/client"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*", "/.well-known/*"]

[[send_email]]
name = "EMAIL"
allowed_sender_addresses = ["noreply@fa.tftt.cc"]

[[r2_buckets]]
binding = "ASSET_BUCKET"
bucket_name = "flareauth-assets"

[[d1_databases]]
binding = "DB"
database_name = "flareauth-db"
database_id = "4214d8e8-6e05-40c2-ba56-80e5c5ba965a"
migrations_dir = "./migrations"

[[queues.producers]]
binding = "EMAIL_QUEUE"
queue = "flareauth-email"

[triggers]
crons = ["*/15 * * * *"]

[observability]
enabled = true
