import {
  addMemberRequestSchema,
  apiPermissionParam,
  apiPermissionResponseSchema,
  apiResourceResponseSchema,
  apiScopeParam,
  apiScopeResponseSchema,
  applicationIdParam,
  applicationResponseSchema,
  assignmentRoutes,
  createApiPermissionRequestSchema,
  createApiResourceRequestSchema,
  createApiScopeRequestSchema,
  createApplicationRequestSchema,
  createApplicationResponseSchema,
  createInvitationRequestSchema,
  createOrganizationRequestSchema,
  createRoleRequestSchema,
  idParam,
  invitationParam,
  jsonBody,
  listApiPermissionsResponseSchema,
  listApiResourcesResponseSchema,
  listApiScopesResponseSchema,
  listApplicationsResponseSchema,
  listClientSecretsResponseSchema,
  listInvitationsResponseSchema,
  listMembersResponseSchema,
  listOrganizationsResponseSchema,
  listRedirectUrisResponseSchema,
  listRolesResponseSchema,
  type ManagementRouteConfig,
  memberParam,
  multipartBody,
  organizationIdParam,
  organizationResponseSchema,
  paginationQuerySchema,
  replaceRedirectUrisRequestSchema,
  replaceRolePermissionsRequestSchema,
  rolePermissionsResponseSchema,
  roleResponseSchema,
  rotateClientSecretResponseSchema,
  updateApiPermissionRequestSchema,
  updateApiResourceRequestSchema,
  updateApiScopeRequestSchema,
  updateApplicationRequestSchema,
  updateMemberRequestSchema,
  updateOrganizationRequestSchema,
  updateRoleRequestSchema,
  uploadedAssetResponseSchema,
  z,
} from './helpers'

export const applicationAuthorizationRoutes: ManagementRouteConfig[] = [
  {
    method: 'get',
    path: '/openapi.json',
    operationId: 'getManagementOpenApi',
    summary: 'Get Management OpenAPI document',
    response: z.record(z.string(), z.unknown()),
    security: [],
  },

  {
    method: 'get',
    path: '/applications',
    operationId: 'listApplications',
    summary: 'List applications',
    request: { query: paginationQuerySchema },
    response: listApplicationsResponseSchema,
  },
  {
    method: 'post',
    path: '/applications',
    operationId: 'createApplication',
    summary: 'Create application',
    request: { body: jsonBody(createApplicationRequestSchema) },
    response: createApplicationResponseSchema,
    status: 201,
  },
  {
    method: 'get',
    path: '/applications/{id}',
    operationId: 'getApplication',
    summary: 'Get application',
    request: { params: idParam },
    response: applicationResponseSchema,
  },
  {
    method: 'patch',
    path: '/applications/{id}',
    operationId: 'updateApplication',
    summary: 'Update application',
    request: { params: idParam, body: jsonBody(updateApplicationRequestSchema) },
    response: applicationResponseSchema,
  },
  {
    method: 'delete',
    path: '/applications/{id}',
    operationId: 'deleteApplication',
    summary: 'Delete application',
    request: { params: idParam },
    noBody: true,
  },
  {
    method: 'post',
    path: '/applications/{applicationId}/logo',
    operationId: 'uploadApplicationLogo',
    summary: 'Upload application logo',
    request: { params: applicationIdParam, body: multipartBody() },
    response: uploadedAssetResponseSchema,
    status: 201,
  },
  {
    method: 'get',
    path: '/applications/{id}/redirect-uris',
    operationId: 'listRedirectUris',
    summary: 'List application redirect URIs',
    request: { params: idParam, query: paginationQuerySchema },
    response: listRedirectUrisResponseSchema,
  },
  {
    method: 'put',
    path: '/applications/{id}/redirect-uris',
    operationId: 'replaceRedirectUris',
    summary: 'Replace application redirect URIs',
    request: { params: idParam, body: jsonBody(replaceRedirectUrisRequestSchema) },
    response: listRedirectUrisResponseSchema,
  },
  {
    method: 'get',
    path: '/applications/{id}/client-secrets',
    operationId: 'listClientSecrets',
    summary: 'List application client secrets',
    request: { params: idParam, query: paginationQuerySchema },
    response: listClientSecretsResponseSchema,
  },
  {
    method: 'post',
    path: '/applications/{id}/client-secrets',
    operationId: 'rotateClientSecret',
    summary: 'Rotate application client secret',
    request: { params: idParam },
    response: rotateClientSecretResponseSchema,
    status: 201,
  },

  {
    method: 'get',
    path: '/api-resources',
    operationId: 'listApiResources',
    summary: 'List API resources',
    request: { query: paginationQuerySchema },
    response: listApiResourcesResponseSchema,
  },
  {
    method: 'post',
    path: '/api-resources',
    operationId: 'createApiResource',
    summary: 'Create API resource',
    request: { body: jsonBody(createApiResourceRequestSchema) },
    response: apiResourceResponseSchema,
    status: 201,
  },
  {
    method: 'get',
    path: '/api-resources/{id}',
    operationId: 'getApiResource',
    summary: 'Get API resource',
    request: { params: idParam },
    response: apiResourceResponseSchema,
  },
  {
    method: 'patch',
    path: '/api-resources/{id}',
    operationId: 'updateApiResource',
    summary: 'Update API resource',
    request: { params: idParam, body: jsonBody(updateApiResourceRequestSchema) },
    response: apiResourceResponseSchema,
  },
  {
    method: 'delete',
    path: '/api-resources/{id}',
    operationId: 'deleteApiResource',
    summary: 'Delete API resource',
    request: { params: idParam },
    noBody: true,
  },
  {
    method: 'get',
    path: '/api-resources/{id}/scopes',
    operationId: 'listApiResourceScopes',
    summary: 'List API resource scopes',
    request: { params: idParam, query: paginationQuerySchema },
    response: listApiScopesResponseSchema,
  },
  {
    method: 'post',
    path: '/api-resources/{id}/scopes',
    operationId: 'createApiResourceScope',
    summary: 'Create API resource scope',
    request: { params: idParam, body: jsonBody(createApiScopeRequestSchema) },
    response: apiScopeResponseSchema,
    status: 201,
  },
  {
    method: 'patch',
    path: '/api-resources/{id}/scopes/{scopeId}',
    operationId: 'updateApiResourceScope',
    summary: 'Update API resource scope',
    request: { params: apiScopeParam, body: jsonBody(updateApiScopeRequestSchema) },
    response: apiScopeResponseSchema,
  },
  {
    method: 'delete',
    path: '/api-resources/{id}/scopes/{scopeId}',
    operationId: 'deleteApiResourceScope',
    summary: 'Delete API resource scope',
    request: { params: apiScopeParam },
    noBody: true,
  },
  {
    method: 'get',
    path: '/api-resources/{id}/permissions',
    operationId: 'listApiResourcePermissions',
    summary: 'List API resource permissions',
    request: { params: idParam, query: paginationQuerySchema },
    response: listApiPermissionsResponseSchema,
  },
  {
    method: 'post',
    path: '/api-resources/{id}/permissions',
    operationId: 'createApiResourcePermission',
    summary: 'Create API resource permission',
    request: { params: idParam, body: jsonBody(createApiPermissionRequestSchema) },
    response: apiPermissionResponseSchema,
    status: 201,
  },
  {
    method: 'patch',
    path: '/api-resources/{id}/permissions/{permissionId}',
    operationId: 'updateApiResourcePermission',
    summary: 'Update API resource permission',
    request: { params: apiPermissionParam, body: jsonBody(updateApiPermissionRequestSchema) },
    response: apiPermissionResponseSchema,
  },
  {
    method: 'delete',
    path: '/api-resources/{id}/permissions/{permissionId}',
    operationId: 'deleteApiResourcePermission',
    summary: 'Delete API resource permission',
    request: { params: apiPermissionParam },
    noBody: true,
  },

  {
    method: 'get',
    path: '/organizations',
    operationId: 'listOrganizations',
    summary: 'List organizations',
    request: { query: paginationQuerySchema },
    response: listOrganizationsResponseSchema,
  },
  {
    method: 'post',
    path: '/organizations',
    operationId: 'createOrganization',
    summary: 'Create organization',
    request: { body: jsonBody(createOrganizationRequestSchema) },
    response: organizationResponseSchema,
    status: 201,
  },
  {
    method: 'get',
    path: '/organizations/{id}',
    operationId: 'getOrganization',
    summary: 'Get organization',
    request: { params: idParam },
    response: organizationResponseSchema,
  },
  {
    method: 'patch',
    path: '/organizations/{id}',
    operationId: 'updateOrganization',
    summary: 'Update organization',
    request: { params: idParam, body: jsonBody(updateOrganizationRequestSchema) },
    response: organizationResponseSchema,
  },
  {
    method: 'delete',
    path: '/organizations/{id}',
    operationId: 'deleteOrganization',
    summary: 'Delete organization',
    request: { params: idParam },
    noBody: true,
  },
  {
    method: 'post',
    path: '/organizations/{organizationId}/logo',
    operationId: 'uploadOrganizationLogo',
    summary: 'Upload organization logo',
    request: { params: organizationIdParam, body: multipartBody() },
    response: uploadedAssetResponseSchema,
    status: 201,
  },
  {
    method: 'get',
    path: '/organizations/{id}/members',
    operationId: 'listOrganizationMembers',
    summary: 'List organization members',
    request: { params: idParam, query: paginationQuerySchema },
    response: listMembersResponseSchema,
  },
  {
    method: 'post',
    path: '/organizations/{id}/members',
    operationId: 'createOrganizationMember',
    summary: 'Create organization member',
    request: { params: idParam, body: jsonBody(addMemberRequestSchema) },
    response: z.object({ member: z.unknown() }),
    status: 201,
  },
  {
    method: 'patch',
    path: '/organizations/{id}/members/{memberId}',
    operationId: 'updateOrganizationMember',
    summary: 'Update organization member',
    request: { params: memberParam, body: jsonBody(updateMemberRequestSchema) },
    response: z.object({ member: z.unknown() }),
  },
  {
    method: 'delete',
    path: '/organizations/{id}/members/{memberId}',
    operationId: 'deleteOrganizationMember',
    summary: 'Delete organization member',
    request: { params: memberParam },
    noBody: true,
  },
  {
    method: 'get',
    path: '/organizations/{id}/invitations',
    operationId: 'listOrganizationInvitations',
    summary: 'List organization invitations',
    request: { params: idParam, query: paginationQuerySchema },
    response: listInvitationsResponseSchema,
  },
  {
    method: 'post',
    path: '/organizations/{id}/invitations',
    operationId: 'createOrganizationInvitation',
    summary: 'Create organization invitation',
    request: { params: idParam, body: jsonBody(createInvitationRequestSchema) },
    response: z.object({ invitation: z.unknown() }),
    status: 201,
  },
  {
    method: 'delete',
    path: '/organizations/{id}/invitations/{invitationId}',
    operationId: 'deleteOrganizationInvitation',
    summary: 'Delete organization invitation',
    request: { params: invitationParam },
    noBody: true,
  },

  {
    method: 'get',
    path: '/roles',
    operationId: 'listRoles',
    summary: 'List roles',
    request: { query: paginationQuerySchema },
    response: listRolesResponseSchema,
  },
  {
    method: 'post',
    path: '/roles',
    operationId: 'createRole',
    summary: 'Create role',
    request: { body: jsonBody(createRoleRequestSchema) },
    response: roleResponseSchema,
    status: 201,
  },
  {
    method: 'get',
    path: '/roles/{id}',
    operationId: 'getRole',
    summary: 'Get role',
    request: { params: idParam },
    response: roleResponseSchema,
  },
  {
    method: 'patch',
    path: '/roles/{id}',
    operationId: 'updateRole',
    summary: 'Update role',
    request: { params: idParam, body: jsonBody(updateRoleRequestSchema) },
    response: roleResponseSchema,
  },
  {
    method: 'delete',
    path: '/roles/{id}',
    operationId: 'deleteRole',
    summary: 'Delete role',
    request: { params: idParam },
    noBody: true,
  },
  {
    method: 'get',
    path: '/roles/{id}/permissions',
    operationId: 'listRolePermissions',
    summary: 'List role permissions',
    request: { params: idParam },
    response: rolePermissionsResponseSchema,
  },
  {
    method: 'put',
    path: '/roles/{id}/permissions',
    operationId: 'replaceRolePermissions',
    summary: 'Replace role permissions',
    request: { params: idParam, body: jsonBody(replaceRolePermissionsRequestSchema) },
    noBody: true,
  },
  ...assignmentRoutes(),
]
