import {
  jsonBody,
  listManagementUserApplicationsResponseSchema,
  listManagementUserLinkedAccountsResponseSchema,
  listManagementUserPasskeysResponseSchema,
  listManagementUserSessionsResponseSchema,
  listManagementUsersResponseSchema,
  type ManagementRouteConfig,
  managementBanUserRequestSchema,
  managementCreateUserRequestSchema,
  managementPasswordResetRequestSchema,
  managementUpdateUserRequestSchema,
  managementUserDetailResponseSchema,
  managementUserSecurityResponseSchema,
  paginationQuerySchema,
  securityPolicySchema,
  updateSecurityPolicySchema,
  userIdParam,
  userPasskeyParam,
  userSessionParam,
  z,
} from './helpers'

export const userSecurityRoutes: ManagementRouteConfig[] = [
  {
    method: 'get',
    path: '/users',
    operationId: 'listUsers',
    summary: 'List users',
    response: listManagementUsersResponseSchema,
  },
  {
    method: 'post',
    path: '/users',
    operationId: 'createUser',
    summary: 'Create user',
    request: { body: jsonBody(managementCreateUserRequestSchema) },
    response: managementUserDetailResponseSchema,
    status: 201,
  },
  {
    method: 'get',
    path: '/users/{id}',
    operationId: 'getUser',
    summary: 'Get user',
    request: { params: userIdParam },
    response: managementUserDetailResponseSchema,
  },
  {
    method: 'patch',
    path: '/users/{id}',
    operationId: 'updateUser',
    summary: 'Update user',
    request: { params: userIdParam, body: jsonBody(managementUpdateUserRequestSchema) },
    response: managementUserDetailResponseSchema,
  },
  {
    method: 'delete',
    path: '/users/{id}',
    operationId: 'deleteUser',
    summary: 'Delete user',
    request: { params: userIdParam },
    noBody: true,
  },
  {
    method: 'put',
    path: '/users/{id}/ban',
    operationId: 'banUser',
    summary: 'Ban user',
    request: { params: userIdParam, body: jsonBody(managementBanUserRequestSchema) },
    response: managementUserDetailResponseSchema,
  },
  {
    method: 'post',
    path: '/users/{id}/ban',
    operationId: 'banUserCompatibility',
    summary: 'Ban user',
    request: { params: userIdParam, body: jsonBody(managementBanUserRequestSchema) },
    response: managementUserDetailResponseSchema,
  },
  {
    method: 'delete',
    path: '/users/{id}/ban',
    operationId: 'unbanUser',
    summary: 'Unban user',
    request: { params: userIdParam },
    response: managementUserDetailResponseSchema,
  },
  {
    method: 'post',
    path: '/users/{id}/unban',
    operationId: 'unbanUserCompatibility',
    summary: 'Unban user',
    request: { params: userIdParam },
    response: managementUserDetailResponseSchema,
  },
  {
    method: 'post',
    path: '/users/password-reset',
    operationId: 'requestUserPasswordResetCompatibility',
    summary: 'Create user password reset request',
    request: { body: jsonBody(managementPasswordResetRequestSchema) },
    response: z.object({ ok: z.boolean() }),
  },
  {
    method: 'post',
    path: '/users/password-reset-requests',
    operationId: 'createUserPasswordResetRequest',
    summary: 'Create user password reset request',
    request: { body: jsonBody(managementPasswordResetRequestSchema) },
    response: z.object({ ok: z.boolean() }),
  },
  {
    method: 'post',
    path: '/users/{id}/password-reset-requests',
    operationId: 'createUserPasswordResetRequestById',
    summary: 'Create user password reset request',
    request: { params: userIdParam },
    response: z.object({ ok: z.boolean() }),
  },
  {
    method: 'get',
    path: '/users/{id}/sessions',
    operationId: 'listUserSessions',
    summary: 'List user sessions',
    request: { params: userIdParam, query: paginationQuerySchema },
    response: listManagementUserSessionsResponseSchema,
  },
  {
    method: 'delete',
    path: '/users/{id}/sessions',
    operationId: 'deleteUserSessions',
    summary: 'Delete user sessions',
    request: { params: userIdParam },
    noBody: true,
  },
  {
    method: 'delete',
    path: '/users/{id}/sessions/{sessionId}',
    operationId: 'deleteUserSession',
    summary: 'Delete user session',
    request: { params: userSessionParam },
    noBody: true,
  },
  {
    method: 'get',
    path: '/users/{id}/linked-accounts',
    operationId: 'listUserLinkedAccounts',
    summary: 'List user linked accounts',
    request: { params: userIdParam, query: paginationQuerySchema },
    response: listManagementUserLinkedAccountsResponseSchema,
  },
  {
    method: 'get',
    path: '/users/{id}/applications',
    operationId: 'listUserApplications',
    summary: 'List user applications',
    request: { params: userIdParam, query: paginationQuerySchema },
    response: listManagementUserApplicationsResponseSchema,
  },
  {
    method: 'get',
    path: '/users/{id}/security',
    operationId: 'getUserSecurity',
    summary: 'Get user security',
    request: { params: userIdParam },
    response: managementUserSecurityResponseSchema,
  },
  {
    method: 'get',
    path: '/users/{id}/passkeys',
    operationId: 'listUserPasskeys',
    summary: 'List user passkeys',
    request: { params: userIdParam, query: paginationQuerySchema },
    response: listManagementUserPasskeysResponseSchema,
  },
  {
    method: 'delete',
    path: '/users/{id}/passkeys/{passkeyId}',
    operationId: 'deleteUserPasskey',
    summary: 'Delete user passkey',
    request: { params: userPasskeyParam },
    noBody: true,
  },

  {
    method: 'get',
    path: '/security/policy',
    operationId: 'getSecurityPolicy',
    summary: 'Get security policy',
    response: z.object({ policy: securityPolicySchema }),
  },
  {
    method: 'patch',
    path: '/security/policy',
    operationId: 'updateSecurityPolicy',
    summary: 'Update security policy',
    request: { body: jsonBody(updateSecurityPolicySchema) },
    response: z.object({ policy: securityPolicySchema }),
  },
  {
    method: 'get',
    path: '/security/users/{id}',
    operationId: 'getSecurityUser',
    summary: 'Get security user',
    request: { params: userIdParam },
    response: managementUserDetailResponseSchema,
  },
  {
    method: 'get',
    path: '/security/users/{id}/sessions',
    operationId: 'listSecurityUserSessions',
    summary: 'List security user sessions',
    request: { params: userIdParam, query: paginationQuerySchema },
    response: listManagementUserSessionsResponseSchema,
  },
  {
    method: 'delete',
    path: '/security/users/{id}/sessions',
    operationId: 'deleteSecurityUserSessions',
    summary: 'Delete security user sessions',
    request: { params: userIdParam },
    noBody: true,
  },
  {
    method: 'delete',
    path: '/security/users/{id}/sessions/{sessionId}',
    operationId: 'deleteSecurityUserSession',
    summary: 'Delete security user session',
    request: { params: userSessionParam },
    noBody: true,
  },
  {
    method: 'get',
    path: '/security/users/{id}/passkeys',
    operationId: 'listSecurityUserPasskeys',
    summary: 'List security user passkeys',
    request: { params: userIdParam, query: paginationQuerySchema },
    response: listManagementUserPasskeysResponseSchema,
  },
  {
    method: 'delete',
    path: '/security/users/{id}/passkeys/{passkeyId}',
    operationId: 'deleteSecurityUserPasskey',
    summary: 'Delete security user passkey',
    request: { params: userPasskeyParam },
    noBody: true,
  },
]
